### ISSUE TITLE
Add better metadata for SEO

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/stealjs#113]
Implement the same/similar changes to as what’s in these two PRs:

- https://github.com/canjs/bit-docs-html-canjs/pull/535
- https://github.com/canjs/canjs/pull/5022

**Comment by chasenlehara** [comment]
@cherifGsoul Did you get the permissions you needed to publish this?

**Comment by cherifGsoul** [comment]
@chasenlehara Yeah, is fixed in https://github.com/stealjs/bit-docs-stealjs-theme/pull/4
