### ISSUE TITLE
Loading from CDN guide

### ISSUE THREAD

**Issue by pYr0x** [stealjs/stealjs#28]
the loading from CDN guide is gone on the new steal 1.0 website?

old website:
http://stealjs.com/docs/StealJS.loading-from-cdn.html

**Comment by matthewp** [comment]
I don't recall doing this on purpose. Let me look.

**Comment by matthewp** [comment]
That doc is not in the latest RC for some reason. I'll try again when I release steal 1.0

**Comment by matthewp** [comment]
It is fixed: http://stealjs.com/docs/StealJS.loading-from-cdn.html
