### ISSUE TITLE
Use a high-DPI image for the logo on the home page

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/stealjs#30]
Here’s the current one:
<img width="786" alt="screen shot 2016-12-27 at 12 22 27 pm" src="https://cloud.githubusercontent.com/assets/10070176/21507657/2fa917b8-cc2f-11e6-928a-15dc42360588.png">

**Comment by marshallswain** [comment]
We could also use SVG and text.  We already have the SVG, just needs some markup.
