### ISSUE TITLE
No docs for the plugins configuration

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/stealjs#34]
I was expecting to find docs for the plugins configuration from either of these two pages:
- https://stealjs.com/docs/steal.html
- https://stealjs.com/docs/StealJS.configuration.html

Are there any docs for configuring `plugins` in your `package.json`?

**Comment by pYr0x** [comment]
I think there are in the migration guide

**Comment by chasenlehara** [comment]
Yeah, I helped with those, but I think there should be docs for people who _aren’t_ migrating and want to understand the plugins configuration.

**Comment by pYr0x** [comment]
you are right.
