### ISSUE TITLE
Homepage dropdown is different from the one in docs

### ISSUE THREAD

**Issue by m-mujica** [stealjs/stealjs#4]
I guess we should be using the same dropdown the new CanJS site using cc: @matthewp

**Comment by matthewp** [comment]
Which drop-down are you referring to?

**Comment by m-mujica** [comment]
so you're telling me you can't read minds :D 

![screen shot 2016-11-04 at 15 50 33](https://cloud.githubusercontent.com/assets/724877/20018445/7d85611a-a2a6-11e6-9821-cad73bb662f3.png)


![screen shot 2016-11-04 at 15 50 27](https://cloud.githubusercontent.com/assets/724877/20018451/8458b848-a2a6-11e6-8345-285997555b3b.png)
