### ISSUE TITLE
Certain pages missing Content-Language meta tag

### ISSUE THREAD

**Issue by imaustink** [stealjs/stealjs#44]
Google Chrome's translator is triggered by [this page](https://stealjs.com/docs/StealJS.guides.progressive_loading.html) in particular.
![image](https://cloud.githubusercontent.com/assets/6282922/25444379/bcc2807e-2a5f-11e7-8739-17c6db3e8093.png)

**Comment by m-mujica** [comment]
@imaustink thanks for reporting!
