### ISSUE TITLE
Use double quotes consistently in html attributes

### ISSUE THREAD

**Issue by m-mujica** [stealjs/stealjs#46]
```html
 <!doctype html>
 <html lang="en">
   <head>
       <meta charset="utf-8">
       <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="./dist/bundles/myhub/myhub.css" rel="stylesheet">
    </head>
    <body>
  => <div class='container'>Hello World.</div>
       <script src="./dist/bundles/myhub/myhub.js"></script>
    </body>
  </html>
```

![twitching-sheldon](https://cloud.githubusercontent.com/assets/724877/26163071/ba189520-3ae5-11e7-9162-ba3f2dec7af8.gif)

**Comment by matthewp** [comment]
👍

**Comment by m-mujica** [comment]
Went  through `stealjs/stealjs` deps, ran the following command

```
ag "=\'" --markdown
```
and got some matches in steal (expected) and steal-tools

- [ ] steal (https://github.com/stealjs/steal/pull/1204)
- [x] steal-conditional
- [x] steal-css
- [x] steal-less
- [x] steal-mocha
- [x] steal-qunit
- [x] steal-socket.io
- [ ] steal-tools (https://github.com/stealjs/steal-tools/pull/714)

Silver searcher FTW!

![screen shot 2017-05-18 at 08 35 14](https://cloud.githubusercontent.com/assets/724877/26209008/d3e05be6-3ba8-11e7-8b4a-95dc0aba7457.png)

**Comment by m-mujica** [comment]
docs will be fixed in the next release, just merged the PRs to steal and steal-tools
