### ISSUE TITLE
Bring back the section anchors

### ISSUE THREAD

**Issue by m-mujica** [stealjs/stealjs#5]
I'll implement this with jquery, then we'll see whether to make it its own bit-docs plugin

<img width="230" alt="screen shot 2016-11-04 at 3 04 28 pm" src="https://cloud.githubusercontent.com/assets/724877/20019263/2215307c-a2aa-11e6-98a5-b8cbb19132ab.png">

**Comment by m-mujica** [comment]
@matthewp I just implemented this and published the updated docs. One thing I noticed though is that `bit-docs-html-toc` generates ids with the [format `sig_{{ ELEMENT_TEXT }}`](https://github.com/bit-docs/bit-docs-html-toc/blob/764a2c920846bae00207eca4e3e6859a0a7baf5d/toc.js#L103) and the anchors logic from the steal website generates ids like [`section_{{ ELEMENT_TEXT }}`](https://github.com/bit-docs/bit-docs-docjs-theme/blob/5c1f50c1ea1c6da8e036546ec2bfe4a90474e735/static/docjs.js#L11)

I made it so the docjs-theme doesn't override the ids set the by html-toc, wondering if we should make them generate consistent ids; `section_{{ ELEMENT_TEXT }}` reads better IMO, and not all headings collected by `html-toc` are signature definitions so `section_{{ ELEMENT_TEXT }}` might make more sense.

What do you think?

**Comment by matthewp** [comment]
Yeah, sounds right to me, if you make that change in html-toc make sure to do it in a minor (or major) version, since it would be technically backwards incompatible.

**Comment by m-mujica** [comment]
Fixed and released in bit-docs-html-toc@0.3.0, also stealjs dep updated straight to master because yolo... Closing this one.
