### ISSUE TITLE
Warn if package.json is missing name or version

### ISSUE THREAD

**Issue by imaustink** [stealjs/stealjs#58]
Using `steal` with a project whose `package.json` is missing a name and version causes steal to attempt loading the wrong path, something like `undefined%23js/app.js`. It would be nice to warn the user when their `package.json` is missing anything vital.

**Comment by m-mujica** [comment]
@imaustink thanks for filing the issue. This is steal's website repo though, I'll re-create this issue in stealjs/steal.... confusing repo naming is confusing :P
