### ISSUE TITLE
Steal Needs a method to load assets from imports more easy

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/stealjs#91]
We will often have the case where people will import .html via link rel import
they will put scripts into <template> sections 

now steal needs to be able to load the scripts from that template section of a import document

a link rel import html results in a document fragment attached to the link tag

So steal needs some helpers to act relativ on import documents url 

## TODO
```js
// target all imports crawling needed like with npm-crawl but for import tags and nested import tags.
let IMPORT = window.document.getElementByID('my-import')
let SECTION = IMPORT.getElementById('ie-scripts')
// Result <script src="webRoot/theScriptPath">
```
Thats what we don't want thats the default behavier we need all that script urls relativ to the imported document. so i propose Steal supplys 
```js
let importDoc = window.document.getElementByID('my-import')
let importElement = importDoc.getElementById('ie-scripts') 
let target = window.document.head
let options = { method: 'async', relative: true }
steal.importElement({ from: importDoc, element: importElement, target: window.document.head, options })
```

The Import Element Method will do the following it will select the from document get its url then it will select the target element will check if it is a template element if not it will fail as this stuff is only needed for template elements. this should not never target to import stuff from a import document directly with any other type then template.

this is for special behaviers that exist in the webcomponents specs.

## Special behaviers
- if no target is supplyed it will load it like normal and will not append it it will load that with steal
- if no target is supplyed method is auto ignored as not supported
- if target is supplyed steal will simply append to that via appendChild
- if relativ true it will in any case rewrite the script src attr value to match relativ document path
i think that are the most usefull general generic stuff that will come up for steal next
but this is early stage. It Solves near all needs of canjs developers that want to use can-element with link rel import

**Comment by matthewp** [comment]
You already filed https://github.com/stealjs/rfcs/issues/17 which afaik is the same sort of thing.
